name: sprout_test
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.4.3 <4.0.0"

description: A new Flutter project.

dependencies:
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_native_splash: ^2.4.1
  get: ^4.7.2
  get_storage: ^2.1.1
  google_fonts: ^6.2.1
  intl: ^0.19.0
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pubspec_dependency_sorter: ^1.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/
